### ISSUE TITLE
PDF cleanup

### ISSUE THREAD

**Issue by WhatisRT** [input-output-hk/formal-ledger-specifications#146]
This is a blanket issue for various refactoring and improvements regarding the LaTeX code.

- [X] ~Explain (Agda) notations~
  - [X] ~`record` definitions~ (moved to #258)
  - [X] ~`open` for records~ (moved to #258)
- [X] ~Remove superscripts from `⟦_,...,_⟧` (probably via a typeclass)~ (moved to #258)
- [X] ~Remove `_ᶠᵐ` notation from sums by introducing a typeclass~ (moved to #258)
- [X] ~Potentially unify notations for empty/singleton maps and sets via a typeclass~ (moved to #258)
- [x] Rename `∪ᵐˡ` to `∪ˡ` or `∪⃗`
- [X] ~Replace `≡ᵉ` with `≡` (we may not be able to actually make this replacement in the Agda code, so we may have to do some preprocessing of the LaTeX)~ (moved to #258)
- [X] ~Lots of `mapˢ`. Since we now have a `Functor` class, we can make an instance and write `map` instead~ (moved to #258)
- [X] ~Can we remove `+ᵉ` somehow? We could change `HasAdd` so that `+` can take to different types, and then for a ring define some instances where you can always add natural numbers/integers. But maybe we can do something easier?~ (moved to #258)
- [x] Figure 4: Add space below `RwdAddr`
- [x] Figure 6: Align `actionWellFormed`
- [x] Figure 8 (Functions related to voting)
  - [x] Remove comments
  - [x] Add an alias for `2ℚ`, and explain that any number above `1` is fine
  - [X] ~Potentially replace `ℚ` with a unit interval type~
  - [X] Maybe replace `⟨_,_,_⟩` with `|_|_|_|` for the thresholds table
- [X] Figure 8 (Protocol parameter declarations)
  - [X] ~Can we move `Acnt` elsewhere?~ (moved to #258)
  - [x] Replace `pparamsWellFormed` with a predicate (instead of a boolean predicate), which should look cleaner
  - [X] ~This figure is placed inside `\small`, which is OK, but it'd be better to find some other way to fit it so that the font sizes are consistent.~
  - [x] Maybe rename `minCCSize` to `ccMinSize` for consistency?
  - [x] Maybe rename `ccTermLimit` to `ccMaxTermLength`, since that's what it really is?
- [x] Figure 16 (Types used for CERTS transition system): Remove comments
- [X] ~Figure 25 (Functions used for witnessing)~
  - [X] ~Replace `(utxo ˢ) ⟪$⟫ txins` with a more sensible notation. Ideally we could just write `utxo(txins)` (standard notation for applying a function to a set), but we can't. Maybe we could have a somewhat sensible notation in Agda that we filter out in the PDF with a preprocessor?~ (moved to #258)
  - [X] ~`<$>` is also inappropriate here, but that line has unfinished semantics ATM~ (moved to #258)
- [X] Figure 34 (Types and proofs for the ratification of governance actions)
  - [x] That whole `where` block is quite unwieldy, maybe we can move some parts (like `isHF`) out of it?
  - [X] ~Lots of Agda/Haskell knowledge required here, we should switch as much as possible to more commonly understandable notation (and everything that we can't needs to be explained in the `Notation` section)~ (moved to #258)
- [X] Figure 36 (Calculation of stake distributions)
  - [x] We shouldn't show `SpecProperty` stuff, `sp-∘` in this case
  - [x] The pattern-matching trick in `acceptedBy` to expose the fact that the number isn't `0` (i.e. `x@(suc _)`) is black magic. We shouldn't do this in the figure
- [X] ~Figure 40 (NEWEPOCH transition system)~
  - [X] ~We should at least split this into `EPOCH` and `NEWEPOCH` like the Shelley spec~ (moved to #258)
  - [X] ~The module shenanigans and record updates make this one especially hard to read~ (moved to #258)
  - [X] ~We should replace `sucᵉ` by `... + 1`~ (moved to #258)
- [x] The explanation for Figure 6 (Governance Actions) is weird. The italics should refer to types properly.
- [x] Also render `Ledger/GovernanceActions:threshold` in a nice way to resembles the table of the original CIP, but also does not exceed code width and PDF width.
- [X] ~Explain that multiple cold keys can delegate to a single hot key, which gives it more voting power.~ (moved to #258)
- [x] Remove all occurrences of `\small{` and the closing `} % End: small` and instead adjust geometry/scale of figures globally.
- [x] ~Change notation/symbols to conform more closely with classical mathematical notation.~
- [x] Present fields of the `PParams` record type more compactly so that record can appear on a single page without page or margin overruns.

**Comment by williamdemeo** [comment]
*Remark on the proposal to change some notation/symbols*

This has been bothering me for a while, ever since I proposed we replace our previous symbol `|^` for co-restriction with the equivalent unicode symbol `↾` (`\uprightharpoon`).  The problem with this is that, traditionally, `↾` is used for restriction.

We currently use `|` for restriction and `↾` for corestriction.  I propose we use `↾` for restriction and `↿` (`\upleftharpoon`) for co-restriction.

Similarly, we use `f | X ᶜ` (and `f ↾ Y ᶜ`) for the (co)restriction of `f` to the complement of `X` (`Y`).  I suggest we use `f ↾ X ᶜ` (and `f ↿ Y ᶜ`).

**Comment by WhatisRT** [comment]
> traditionally, `↾` is used for restriction.

I've only seen this notation very rarely. For example, [wikipedia](https://en.wikipedia.org/wiki/Restriction_(mathematics)) mentions it in the article about restriction but uses `|` everywhere in the main body of the text. My original reason for using `|^` for corestriction was that corestriction is [usually](https://en.wikipedia.org/wiki/Corestriction) written with a `|` as well, but the codomain in the superscript, and `^` often indicates superscript when there is no typesetting available (for example `a^b`). So for me, changing `|^` to `↾` made sense because it turns it into a single operator. However, I can see that it'd be confusing if you're used to reading this as restriction (and it is ambiguous). So, as I see it, here are the options:

- Go back to using `|` and `|^`: asymmetric, corestriction is a little ugly, but captures the usual notations
- `|_` and `|^`: can't do it in Agda with the regular `_`, but maybe we can find a unicode one. More ugly, but very clear.
- `↾` and `↿`: non-standard (in the case of corestriction) and very confusing. How are you supposed to remember which is which?

**Comment by williamdemeo** [comment]
Well, I sure hope you're not taking wikipedia's word over mine!

Of course the vertical bar, without the harpoon barb at the top, is a common notation, but I'm guessing it arose out of laziness and it's unfortunate because the vertical bar is overused.

I now see what you meant by |^ and that you were not going for an ascii version of an up-right harpoon, but rather a bar with a superscript, which makes much more sense to me as a notation for co-restriction... especially if we were somehow able to use |_ for restriction.

I believe, to the classically trained at least, f ↾ X is interpreted as a more formal way of writing f | X, so using it for co-restriction is confusing.

I don't agree that using ↾ and ↿ is confusing. "How are you supposed to remember which is which?" ...because we know that the first has always stood for restriction of the domain (not codomain).

In my own writings I have more often than not fell into the habit of using | instead of the up-right harpoon, but when it comes to settling on a precise notational convention for an important library or specification, why not defer to the masters?  

Herbert Enderton's books on set theory and logic are (at least in the US) the standard references for the elementary theory and Enderton uses ↾ for restriction of the domain of a relation (e.g., a function).  So (recognizing the "appeal to authority" fallacy) I still think we should use ↾ for restriction of the domain.

I suppose we shouldn't burn more cycles on this and I apologize for distracting you with a relatively trivial matter.  Obviously it's your decision in the end.

**Comment by williamdemeo** [comment]
Remark on the item, "This figure is placed inside \small, which is OK, but it'd be better to find some other way to fit it so that the font sizes are consistent."

I started putting all code figures inside `\small` blocks because, for some of them, it helps keep the lines within the figure border, and for others I did it just to be consistent... so I thought, since there were no objections, we would put all figures inside `\small` blocks.  However, if normal size font for the code blocks is preferable, I can change them all back and rearrange some lines so they fit within the figure borders.  @WhatisRT, what do you think?

**Comment by williamdemeo** [comment]
I think the figure containing the Protocol Parameter declarations is now 13, so I've edited the item referring to that figure.

**Comment by omelkonian** [comment]
> Also, imho, the code font seems unnecessarily large when we don't use `\small`.

I believe we shouldn't fiddle with LaTeX locally (`\small`), but just keep a consistent style that does not exceed 80-90 columns, and only set the font size globally which you can easily set in the [preamble](https://github.com/input-output-hk/formal-ledger-specifications/blob/master/src/latex/preamble.tex#L13-L25).

In my #217 PR, I just had to apply sane styling to existing files without even looking at the PDF and the result was automagically not overflowing to the right of the page.

**Comment by omelkonian** [comment]
Also note the possibility of using `scalebox{.95}{...}` if you really need to "zoom out" a particular figure (e.g. you do not want to break lines so that a matrix can be discerned).

**Comment by williamdemeo** [comment]
Okay, so I'll remove all the `\small`s... but I'll make a separate PR for that.

**Comment by williamdemeo** [comment]
@WhatisRT Re. the items I didn't get to yet, can I move them to a new issue in the new PI and close this issue?

**Comment by williamdemeo** [comment]
Moved outstanding items to issue #258 in new milestone.
